title = "Upsalafandom"
description = "Sällskap för vetenskaplig vitterhet"
base_url = "__PREFIX__"
generate_rss = true
generate_tags_pages = true
compile_sass = true
taxonomies = [
    { name = "kategorier", rss = true, paginate_by = 10 },
    { name = "taggar", rss = true, paginate_by = 10 },
    { name = "forfattare", rss = true, paginate_by = 10 },
]
default_language = "sv"
